#ifndef CONFIG_H
#define CONFIG_H

#define NING 6
#define BANSERMIN 3
#define BANSERMAX NING
#define TEMPSERMAX 3600
#define TEMPSERINT 1800
#define QTDSERMAX 12
#define TEMPUSUMIN 3
#define TEMPUSUMAX 6
#define USUCHANCEVEG 0.1
#define QTDPORCVAS 30
#define TEMPREPOVAS 20

#endif // CONFIG_H
